name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: ./mvnw clean verify

    - name: Create installable package
      if: ${{ runner.os == 'Linux' }}
      run: .github/scripts/create-linux-package.sh
    - name: Archive debian package
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Linux' }}
      with:
        name: linux-deb-package
        path: target/textcryptor_*.deb
    - name: Archive appimage package
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Linux' }}
      with:
        name: linux-appimage
        path: textcryptor-x86_64.AppImage

    - name: Create installable package
      if: ${{ runner.os == 'macOS' }}
      run: .github/scripts/create-macos-package.sh
    - name: Archive macOS package
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'macOS' }}
      with:
        name: macos-package
        path: target/textcryptor_*.dmg

    - name: Create installable package
      if: ${{ runner.os == 'Windows' }}
      run: .github/scripts/create-windows-package.sh
    - name: Archive Windows package
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Windows' }}
      with:
        name: windows-package
        path: target/textcryptor_*.exe
