name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: ./mvnw clean verify

    - name: Create installable package
      if: ${{ runner.os == 'Linux' }}
      run: .github/scripts/create-linux-package.sh
      shell: bash
    - name: Archive jar
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Linux' }}
      with:
        name: textcryptor-packages
        path: target/textcryptor*.jar
    - name: Archive debian package
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Linux' }}
      with:
        name: textcryptor-packages
        path: target/textcryptor*.deb
    - name: Archive appimage package
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Linux' }}
      with:
        name: textcryptor-packages
        path: textcryptor-x86_64.AppImage

    - name: Create installable package
      if: ${{ runner.os == 'macOS' }}
      run: .github/scripts/create-macos-package.sh
      shell: bash
    - name: Archive macOS package
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'macOS' }}
      with:
        name: textcryptor-packages
        path: target/textcryptor*.dmg

    - name: Create installable package
      if: ${{ runner.os == 'Windows' }}
      run: .github/scripts/create-windows-package.sh
      shell: bash
    - name: Archive Windows package
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Windows' }}
      with:
        name: textcryptor-packages
        path: target/textcryptor*.exe
